image: python:3
lint:
 stage: test
 script:
 - pip install yapf
 - yapf --recursive --style google .
 only:
 - pushes

unittest:
 stage: test
 needs: 
 - pipeline: test
   job: lint
 script:
 - pip install yapf
 - pytest 
 only:
 - pushes